### ISSUE TITLE
Css issue after enabling v2 page cache module

### ISSUE THREAD

**Issue by joshiparthin** [budgetneon/v2pagecache#2] opened 2016-01-27 11:38 UTC
I have followed all the steps as mentioned in https://github.com/budgetneon/v2pagecache.
When cache module is disable, everything works fine. But when i enable cache module, there is some problem with css in front end. I have attached screenshot for both of this cases.
![image1](https://cloud.githubusercontent.com/assets/6594877/12612367/28aa5b58-c518-11e5-8ce0-ebfe07478fa3.png)
![image2](https://cloud.githubusercontent.com/assets/6594877/12612381/47d715c0-c518-11e5-8c86-c0bf9d06eb82.png)

Initially my site loooks as shown in image1.png i.e. When cache module is disable. 
But when i enable cache module , my site looks as shown in image2.png.

Please help us.

**Comment by krschwab** [comment] 2016-01-27 11:43
I"m afraid I can't help much just looking at a screenshot.

If you have a live site that's currently having a problem, I could look.

**Comment by joshiparthin** [comment] 2016-01-28 07:10
Here is the link: http://yieldnotion.com/demos/trendvia/
Right now caching module is enabled. 
Please check it.

**Comment by krschwab** [comment] 2016-01-28 13:33
Unfortunately, that didn't help much.   I don't see any notable errors.  I also don't see the time stamp at the bottom of the source that would indicate the page cache is on.  There's likely something about that theme, or some other plugin you're running that doesn't work well with the page cache.

Most often, the fix is to manually add some pattern to the $skip_urls array, denoting a url that you want the page cache not to cache.

Whatever the issue is, it doesn't appear to be something I can help with remotely.

**Comment by budgetneon** [comment] 2016-01-28 15:01
Closing this.   The pagecache works with the default theme.   3rd party themes require work to research what urls should not be cached and subsequent changes to the configuration.

**Closed as completed by budgetneon** 2016-01-28 15:01 UTC

**Comment by joshiparthin** [comment] 2016-01-29 03:27
But how to decide which urls to be cached and which ones not. ?  

## 

Sincerely, 

Parth Joshi

Startup Techno - Consultant | Corporate Trainer

parthjoshi.in | LinkedIN | Twitter | (M) +91 98252 95947

**Comment by budgetneon** [comment] 2016-01-29 04:48
You would need someone with some web developer level expertise to debug the problem and fix it.   We don't sell this module, and cannot devote time on how to figure that out for the various third party themes, sorry.
