### ISSUE TITLE
Auto Caching

### ISSUE THREAD

**Issue by BrettyWhite** [budgetneon/v2pagecache#3] opened 2016-02-15 14:52 UTC
Hello,

This isn't a bug but I was wondering if there was a reason that we cant auto-cache using something like a sitemap to preload all of the pages using cron or similar time oriented trigger after an expiration of cached files? 

If there wasn't a reason or it wasnt thought of I will personally look into it and contribute what I write.

Thanks

**Comment by budgetneon** [comment] 2016-02-15 16:20
It caches the pages as they are accessed, so you could accomplish this by just crawling the page using curl or a similar tool.

**Comment by BrettyWhite** [comment] 2016-02-16 01:13
A simple JavaScript crawler worked wonders. Thanks for the suggestion.

**Comment by BrettyWhite** [comment] 2016-02-19 00:07
One other thing I noticed was that cached pages do not update the cart information if the person had an item in their cart and viewed a page. I will also look into this, just wanted to make you aware of it. Thanks again for this library.

**Comment by budgetneon** [comment] 2016-02-19 10:28
It shouldn't be returning a cached page if you put something in the cart...here's the section of code:

```
// don't cache if affiliate page, or cart has items in it
    if (!empty($_GET['affiliate']) || !empty($_SESSION['cart']))  {
        $this->oktocache=false;
        return $this->oktocache;
    } 
```

Basically, the caching, and return of cached pages is off for anyone with an item in the cart.

**Comment by budgetneon** [comment] 2016-02-19 10:56
I see the problem now.  Right after version 2.0.3.1, opencart changed the way they handle cart data for sessions....it looks like they may have gotten rid of the cart session key.

**Comment by budgetneon** [comment] 2016-02-19 11:04
Yeah, doesn't look good....it looks like opencart made it so you can't tell if there are items in the cart unless you query the database, which is a pretty heavyweight thing to do for a page cache.

I will close this issue, since the name of the issue isn't right, and open a new issue.

**Comment by budgetneon** [comment] 2016-02-19 11:05
I wil

**Closed as completed by budgetneon** 2016-02-19 11:05 UTC
